"""Metadata extraction from LaTeX preamble."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class ProjectMetadata:
    title_zh: str = ""
    title_en: str = ""
    author_zh: str = ""
    author_en: str = ""
    date: str = ""
    degree: str = ""
    speciality_zh: str = ""
    speciality_en: str = ""
    supervisor_zh: str = ""
    supervisor_en: str = ""
    institution: str = ""
    document_class: str = ""
    chapters: list[dict[str, str]] = field(default_factory=list)
    total_figures: int = 0
    total_references: int = 0

    @property
    def title(self) -> str:
        return self.title_zh or self.title_en or "Untitled"

    @property
    def author(self) -> str:
        if self.author_zh and self.author_en:
            return f"{self.author_en} ({self.author_zh})"
        return self.author_zh or self.author_en or "Unknown"


def extract_metadata(preamble: str, class_options: dict[str, str] = None) -> ProjectMetadata:
    """Extract metadata from LaTeX preamble source."""
    meta = ProjectMetadata()

    # Try thesis template key-value setup blocks (e.g. \ustcsetup, \thesissetup)
    for cmd in ('ustcsetup', 'thesissetup', 'njusetup', 'thusetup'):
        m = re.search(rf'\\{cmd}\s*\{{', preamble)
        if m:
            meta = _parse_kv_setup(preamble, m.start(), meta)
            break
    else:
        # Standard LaTeX metadata
        meta = _parse_standard_metadata(preamble, meta)

    # Document class info
    if class_options:
        meta.degree = class_options.get('degree', '')

    return meta


def _parse_kv_setup(source: str, start: int, meta: ProjectMetadata) -> ProjectMetadata:
    """Parse thesis template key-value metadata block (\\xxxsetup{key=value})."""
    from latex2kb.utils import find_matching_brace

    brace_start = source.find('{', start)
    if brace_start == -1:
        return meta
    brace_end = find_matching_brace(source, brace_start)
    if brace_end == -1:
        return meta

    block = source[brace_start + 1:brace_end]

    # Parse key = {value} pairs
    kv_map = {
        'title': 'title_zh',
        'title*': 'title_en',
        'author': 'author_zh',
        'author*': 'author_en',
        'date': 'date',
        'speciality': 'speciality_zh',
        'speciality*': 'speciality_en',
        'supervisor': 'supervisor_zh',
        'supervisor*': 'supervisor_en',
    }

    for key, attr in kv_map.items():
        # Match: key = {value} or key = value,
        pattern = re.escape(key) + r'\s*=\s*\{([^}]*)\}'
        m = re.search(pattern, block)
        if m:
            setattr(meta, attr, m.group(1).strip())
        else:
            # Try without braces: key = value,
            pattern2 = re.escape(key) + r'\s*=\s*([^,}]+)'
            m2 = re.search(pattern2, block)
            if m2:
                setattr(meta, attr, m2.group(1).strip())

    meta.institution = ""  # user can override via metadata
    return meta


def _parse_standard_metadata(preamble: str, meta: ProjectMetadata) -> ProjectMetadata:
    """Parse standard \\title{}, \\author{}, \\date{} commands."""
    title_m = re.search(r'\\title\s*(?:\[([^\]]*)\])?\s*\{([^}]+)\}', preamble)
    if title_m:
        meta.title_zh = title_m.group(2).strip()
        if title_m.group(1):
            meta.title_en = title_m.group(1).strip()

    author_m = re.search(r'\\author\s*\{([^}]+)\}', preamble)
    if author_m:
        meta.author_zh = author_m.group(1).strip()

    date_m = re.search(r'\\date\s*\{([^}]+)\}', preamble)
    if date_m:
        meta.date = date_m.group(1).strip()

    return meta


def metadata_to_yaml(meta: ProjectMetadata) -> str:
    """Convert metadata to YAML string."""
    lines = []

    def _add(key: str, value: str):
        if value:
            # Escape YAML special chars
            if ':' in value or '"' in value or '\n' in value:
                value = '"' + value.replace('"', '\\"') + '"'
            lines.append(f'{key}: {value}')

    lines.append('# LaTeX project metadata')
    lines.append('# Generated by latex2kb')
    lines.append('')

    if meta.title_zh or meta.title_en:
        lines.append('title:')
        if meta.title_zh:
            lines.append(f'  zh: "{meta.title_zh}"')
        if meta.title_en:
            lines.append(f'  en: "{meta.title_en}"')
    elif meta.title:
        _add('title', meta.title)

    lines.append('')
    if meta.author_zh or meta.author_en:
        lines.append('author:')
        if meta.author_zh:
            lines.append(f'  zh: "{meta.author_zh}"')
        if meta.author_en:
            lines.append(f'  en: "{meta.author_en}"')

    _add('date', meta.date)
    _add('degree', meta.degree)

    if meta.speciality_zh or meta.speciality_en:
        lines.append('speciality:')
        if meta.speciality_zh:
            lines.append(f'  zh: "{meta.speciality_zh}"')
        if meta.speciality_en:
            lines.append(f'  en: "{meta.speciality_en}"')

    if meta.supervisor_zh or meta.supervisor_en:
        lines.append('supervisor:')
        if meta.supervisor_zh:
            lines.append(f'  zh: "{meta.supervisor_zh}"')
        if meta.supervisor_en:
            lines.append(f'  en: "{meta.supervisor_en}"')

    _add('institution', meta.institution)
    _add('document_class', meta.document_class)

    if meta.chapters:
        lines.append('')
        lines.append('chapters:')
        for ch in meta.chapters:
            lines.append(f'  - file: "{ch["file"]}"')
            lines.append(f'    title: "{ch["title"]}"')

    lines.append('')
    _add('total_figures', str(meta.total_figures))
    _add('total_references', str(meta.total_references))

    return '\n'.join(lines)
